### ISSUE TITLE
Review Milestone 4 Release

### ISSUE THREAD

**Issue by tylermeathe** [tylermeathe/LightDeviceDesign#8]
Dr. Palmeri, 

I just uploaded my v0.2.0 release for milestone 4.

I have changed the schematic from Milestone 3 slightly to include the atmega328 chip instead of the shield and have uploaded the board and software for the device for your review.

Thanks,
Tyler

**Comment by tylermeathe** [comment]
@mlp6 

Hi Dr. Palmeri, 

I never received a review on my ECAD and software release and I was just trying to see if you guys can look at it before I start finalizing my mechanical design.

Thanks!
Tyler

**Comment by mlp6** [comment]
Brinnae was helping review these, but I see that she and Matt Brown were never added as Collaborators on the project; can you add them now?

**Comment by mlp6** [comment]
I just took a quick look:
* I think that you'll need a crystal on the board if you are just using the `ATMEGA328`; I think you should be able to find a 16 MHz crystal oscillator in the parts library.
* It doesn't look like the negative lead of your battery is attached to anything, nor is the `GND` connection of your voltage regulator... or actually anything that should be attached to `GND`.  It looks like those connections are not correctly made in the schematic, which is why you didn't get ratlines for those traces.

**Comment by tylermeathe** [comment]
Thanks for looking over @mlp6 ! 

I think my ground is correctly set up, at least when I look at it. I uploaded a picture below. I have both the top and bottom layer set as GND.

![image](https://user-images.githubusercontent.com/37547052/48724788-2b8edd80-ebf8-11e8-8198-e1ac50b1e328.png)

For the ATMEGA328, how do you incorporate the crystal into the board. Is there a specific pin that the crystal should be going into? 

What is Matt Brown's username? I added Brinnae but she hasn't accepted it yet.
